In [29]:
import pandas as pd
import numpy as np

In [21]:
df = pd.read_csv('household_power_consumption_cleaned.csv', sep=';')

In [22]:
numeric_cols = ['Global_active_power','Global_reactive_power','Voltage', 
                'Global_intensity','Sub_metering_1','Sub_metering_2','Sub_metering_3']

In [23]:
df[numeric_cols] = df[numeric_cols].astype(float)

In [24]:
df

,datetime,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,2006-12-16 17:24:00,4.216,0.418,234.84,18.4,0.0,1.0,17.0
1,2006-12-16 17:25:00,5.360,0.436,233.63,23.0,0.0,1.0,16.0
2,2006-12-16 17:26:00,5.374,0.498,233.29,23.0,0.0,2.0,17.0
3,2006-12-16 17:27:00,5.388,0.502,233.74,23.0,0.0,1.0,17.0
4,2006-12-16 17:28:00,3.666,0.528,235.68,15.8,0.0,1.0,17.0
...,...,...,...,...,...,...,...,...
2049275,2010-11-26 20:58:00,0.946,0.000,240.43,4.0,0.0,0.0,0.0
2049276,2010-11-26 20:59:00,0.944,0.000,240.00,4.0,0.0,0.0,0.0
2049277,2010-11-26 21:00:00,0.938,0.000,239.82,3.8,0.0,0.0,0.0
2049278,2010-11-26 21:01:00,0.934,0.000,239.70,3.8,0.0,0.0,0.0
2049279,2010-11-26 21:02:00,0.932,0.000,239.55,3.8,0.0,0.0,0.0

In [27]:
df['datetime'] = pd.to_datetime(df['datetime'], errors='coerce')

In [26]:
df

,datetime,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,2006-12-16 17:24:00,4.216,0.418,234.84,18.4,0.0,1.0,17.0
1,2006-12-16 17:25:00,5.360,0.436,233.63,23.0,0.0,1.0,16.0
2,2006-12-16 17:26:00,5.374,0.498,233.29,23.0,0.0,2.0,17.0
3,2006-12-16 17:27:00,5.388,0.502,233.74,23.0,0.0,1.0,17.0
4,2006-12-16 17:28:00,3.666,0.528,235.68,15.8,0.0,1.0,17.0
...,...,...,...,...,...,...,...,...
2049275,2010-11-26 20:58:00,0.946,0.000,240.43,4.0,0.0,0.0,0.0
2049276,2010-11-26 20:59:00,0.944,0.000,240.00,4.0,0.0,0.0,0.0
2049277,2010-11-26 21:00:00,0.938,0.000,239.82,3.8,0.0,0.0,0.0
2049278,2010-11-26 21:01:00,0.934,0.000,239.70,3.8,0.0,0.0,0.0
2049279,2010-11-26 21:02:00,0.932,0.000,239.55,3.8,0.0,0.0,0.0

In [28]:
df['hour'] = df['datetime'].dt.hour
df['day_of_week'] = df['datetime'].dt.dayofweek

In [ ]:
df['hour']

In [ ]:
df['day_of_week']

In [30]:
df['hour_sin'] = np.sin(2 * np.pi * df['hour']/24)
df['hour_cos'] = np.cos(2 * np.pi * df['hour']/24)

In [33]:
df['hour_sin']

0         -0.965926
1         -0.965926
2         -0.965926
3         -0.965926
4         -0.965926
             ...
2049275   -0.866025
2049276   -0.866025
2049277   -0.707107
2049278   -0.707107
2049279   -0.707107
Name: hour_sin, Length: 2049280, dtype: float64

In [32]:
df['hour_cos']

0         -0.258819
1         -0.258819
2         -0.258819
3         -0.258819
4         -0.258819
             ...
2049275    0.500000
2049276    0.500000
2049277    0.707107
2049278    0.707107
2049279    0.707107
Name: hour_cos, Length: 2049280, dtype: float64

In [34]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
scaler_std = StandardScaler()
scaler_minmax = MinMaxScaler()

In [35]:
df_std = pd.DataFrame(scaler_std.fit_transform(df[numeric_cols]), columns=numeric_cols)

In [36]:
df_std

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,2.955077,2.610721,-1.851816,3.098789,-0.182337,-0.051274,1.249421
1,4.037085,2.770406,-2.225274,4.133800,-0.182337,-0.051274,1.130897
2,4.050326,3.320432,-2.330213,4.133800,-0.182337,0.120487,1.249421
3,4.063567,3.355917,-2.191324,4.133800,-0.182337,-0.051274,1.249421
4,2.434881,3.586573,-1.592556,2.513782,-0.182337,-0.051274,1.249421
...,...,...,...,...,...,...,...
2049275,-0.137724,-1.097519,-0.126500,-0.141247,-0.182337,-0.223036,-0.765477
2049276,-0.139616,-1.097519,-0.259217,-0.141247,-0.182337,-0.223036,-0.765477
2049277,-0.145291,-1.097519,-0.314772,-0.186248,-0.182337,-0.223036,-0.765477
2049278,-0.149074,-1.097519,-0.351810,-0.186248,-0.182337,-0.223036,-0.765477
2049279,-0.150966,-1.097519,-0.398106,-0.186248,-0.182337,-0.223036,-0.765477

In [37]:
df_minmax = pd.DataFrame(scaler_minmax.fit_transform(df[numeric_cols]), columns=numeric_cols)

In [38]:
df_minmax

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,0.374796,0.300719,0.376090,0.377593,0.0,0.0125,0.548387
1,0.478363,0.313669,0.336995,0.473029,0.0,0.0125,0.516129
2,0.479631,0.358273,0.326010,0.473029,0.0,0.0250,0.548387
3,0.480898,0.361151,0.340549,0.473029,0.0,0.0125,0.548387
4,0.325005,0.379856,0.403231,0.323651,0.0,0.0125,0.548387
...,...,...,...,...,...,...,...
2049275,0.078762,0.000000,0.556704,0.078838,0.0,0.0000,0.000000
2049276,0.078580,0.000000,0.542811,0.078838,0.0,0.0000,0.000000
2049277,0.078037,0.000000,0.536995,0.074689,0.0,0.0000,0.000000
2049278,0.077675,0.000000,0.533118,0.074689,0.0,0.0000,0.000000
2049279,0.077494,0.000000,0.528271,0.074689,0.0,0.0000,0.000000

In [39]:
df['Apparent_Power'] = (df['Global_active_power']**2 + df['Global_reactive_power']**2)**0.5

In [40]:
df['Apparent_Power']

0          4.236671
1          5.377704
2          5.397025
3          5.411335
4          3.703828
             ...
2049275    0.946000
2049276    0.944000
2049277    0.938000
2049278    0.934000
2049279    0.932000
Name: Apparent_Power, Length: 2049280, dtype: float64

In [41]:
df.to_csv('features.csv', index=False)